# STORE PARAMETERS HERE 
# NUMBER OF DIMENSIONS, PROCESS FREQ ETC

# TODO: 

# SYSTEM_TYPE 

PRINTING_FREQ = 50
LOGGING_FREQ = 100
CONTROLLER_FREQ = 200
OBSERVER_FREQ = 1000

# DIMENSIONS
STATE_DIM = 2
CONTROL_DIM = 1
OUTPUT_DIM = 2
MEASUREMENTS_DIM = 4
USER_INPUTS_DIM = 6

# CHANNELS NAMES
CONTROLLER_CHANEL = "CONTROLLER" 
USER_CHANNEL = "USER"
PLANT_CHANNEL = "PLANT"