# STORE PARAMETERS HERE 
# NUMBER OF DIMENSIONS, PROCESS FREQ ETC

# TODO: 

# SYSTEM_TYPE 

PRINTING_FREQ = 50
LOGGING_FREQ = 100
CONTROLLER_FREQ = 200
OBSERVER_FREQ = 1000

# DIMENSIONS
STATE_DIM = 2
OUTPUT_DIM = 1
INPUT_DIM = 1
MEASUREMENTS_DIM = 1
USER_INPUT_DIM = 1

# CHANNELS NAMES
CONTROLLER_CHANEL = "CONTROLLER" 
USER_CHANNEL = "USER"
