"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class plant_states_t(object):
    __slots__ = ["timestamp", "measurements", "plant_output", "error_code"]

    __typenames__ = ["int64_t", "double", "double", "int32_t"]

    __dimensions__ = [None, [4], [2], None]

    def __init__(self):
        self.timestamp = 0
        self.measurements = [ 0.0 for dim0 in range(4) ]
        self.plant_output = [ 0.0 for dim0 in range(2) ]
        self.error_code = 0

    def encode(self):
        buf = BytesIO()
        buf.write(plant_states_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.timestamp))
        buf.write(struct.pack('>4d', *self.measurements[:4]))
        buf.write(struct.pack('>2d', *self.plant_output[:2]))
        buf.write(struct.pack(">i", self.error_code))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != plant_states_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return plant_states_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = plant_states_t()
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        self.measurements = struct.unpack('>4d', buf.read(32))
        self.plant_output = struct.unpack('>2d', buf.read(16))
        self.error_code = struct.unpack(">i", buf.read(4))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if plant_states_t in parents: return 0
        tmphash = (0xbb6613839ffb44f4) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if plant_states_t._packed_fingerprint is None:
            plant_states_t._packed_fingerprint = struct.pack(">Q", plant_states_t._get_hash_recursive([]))
        return plant_states_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", plant_states_t._get_packed_fingerprint())[0]

